#!/bin/bash

sudo apt-get install python-software-properties software-properties-common -y
sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo yum install php phpmyadmin apache2 mysql-server php7.1-mysql zip -y
cd /var/www/html
sudo wget https://en-gb.wordpress.org/wordpress-4.8.1-en_GB.zip
sudo unzip wordpress-4.8.1-en_GB.zip
cd 
cd ..
sudo chown www-data:www-data html*
sudo ln -s /etc/phpmyadmin/apache.conf /etc/apache2/conf-available/phpmyadmin.conf
sudo a2enconf phpmyadmin.conf
sudo a2enmod rewrite
sudo service apache2 restart
cd /var/www/html
# sudo rm -R wp-content
# sudo mkdir wp-content

#for Azure
# sudo mount -t cifs //wordpress.file.core.windows.net/wp-content/wp-content /var/www/html/wp-content -o vers=3.0,username=wordpress,password=ePnCl3GDCbXX0A2LBaC38l7L281KYJhnGeg42ZXSrjFbUSr/QABUyCSgpVKxLw7+mFf3MyRPGTFv/hE3djPhWg==,dir_mode=0755,file_mode=0755,uid=www-data,gid=www-data,serverino
# sudo bash -c 'echo "//wordpress.file.core.windows.net/wpcontent/wp-content /var/www/html/wp-content /mymountpoint cifs vers=3.0,username=wordpress,password=6oXGMu8rlr0ygkz/3lkF17torrHwUiJkMaHqpD9boA2crb+/P2CI16GbnKq3/6d1HrhRukuMRfCrrQxwuKbCYQ,dir_mode=0755,file_mode=0755,uid=www-data,gid=www-data,serverino" >> /etc/fstab'

# sudo mount -t cifs //wordpress.file.core.windows.net/wp-content [mount point] -o vers=3.0,username=wordpress,password=ePnCl3GDCbXX0A2LBaC38l7L281KYJhnGeg42ZXSrjFbUSr/QABUyCSgpVKxLw7+mFf3MyRPGTFv/hE3djPhWg==,dir_mode=0777,file_mode=0777,sec=ntlmssp

#!/bin/bash
yum update -y
yum install httpd php php-mysql stress -y
cd /etc/httpd/conf
cp httpd.conf httpdconfbackup.conf
rm -rf httpd.conf
wget https://s3-eu-west-1.amazonaws.com/acloudguru-wp/httpd.conf
cd /var/www/html
echo "healthy" > healthy.html
wget https://wordpress.org/latest.tar.gz
tar -xzf latest.tar.gz
cp -r wordpress/* /var/www/html/
rm -rf wordpress
rm -rf latest.tar.gz
chmod -R 755 wp-content
chown -R apache:apache wp-content
service httpd start
chkconfig httpd on